### ISSUE TITLE
Error: (e || "").replace is not a function

### ISSUE THREAD

**Issue by bakermat** [CumulusDS/get-yaml-paths-action#21]
I've got a simple YAML file but when trying to parse it I get:
`Error: (e || "").replace is not a function`

This was with a file.yml file in the root of the repo.

My code: 

      - name: parse config
        id: parseconfig
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: file.yml
          shortname: shortname
          search: search
          version: version
          app: app

![image](https://user-images.githubusercontent.com/12652989/120850656-01b02300-c578-11eb-8a2b-f4b895946216.png)

Any thoughts?

PS: does the `file` also support wildcards, or is it only one file at a time?

**Comment by justinmdudley** [comment]
I was having this issue as well. I had some entries in my .yml file that were numbers and strings with hyphens. I wrapped them in quotes and the issue was resolved.

**Comment by joshuanapoli** [comment]
Could you show a .yml file that exhibits this problem? I'm not sure where the `.replace` error comes from.
