### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by ChristopherBeltran** [CumulusDS/get-yaml-paths-action#54]
Receiving a warning for the deprecated `set-output` command.  

<img width="1106" alt="Screenshot 2022-12-14 at 4 18 55 PM" src="https://user-images.githubusercontent.com/34382621/207736168-2878f63a-1fa7-4dee-bbb1-707fb0b963a8.png">

**Comment by joshuanapoli** [comment]
Thanks; I'll fix the deprecated command warning.
