### ISSUE TITLE
no such file or directory, open file path 

### ISSUE THREAD

**Issue by omkarkhatavkar** [CumulusDS/get-yaml-paths-action#60]
It is not clear how to pass the path of file I tried multiple ways did not worked out well for me, here it is my try : https://github.com/omkarkhatavkar/robottelo/actions/runs/4742431874/jobs/8420698576?pr=98  
```
Warning: Unexpected input(s) 'tests', valid inputs are ['file']
Run CumulusDS/get-yaml-paths-action@v1.0.1
[Error: ENOENT: no such file or directory, open './tests.yml'] {
  errno: -[2](https://github.com/omkarkhatavkar/robottelo/actions/runs/4742431874/jobs/8420698576?pr=98#step:2:2),
  code: 'ENOENT',
  syscall: 'open',
  path: './tests.yml'
}
```

**Comment by joshuanapoli** [comment]
You might have a typo in the name of "tests.yml". It looks like it's spelled "tests.yaml" with an 'a' in your repo. See https://github.com/omkarkhatavkar/robottelo/blob/a23ecbe09ae301ca9838dc710f861483058a75bb/tests.yaml

**Comment by joshuanapoli** [comment]
I'll close this issue, since there hasn't been a reply.
