### ISSUE TITLE
Unexpected input 'xxx', valid inputs are ['file']

### ISSUE THREAD

**Issue by missedone** [CumulusDS/get-yaml-paths-action#7]
hi, thanks for the action, it works well except the warning:
`Unexpected input 'xxx', valid inputs are ['file']`

in the action.xml, it defines only one input pram `file`, i understand the other param name is dynamic, but the warning makes the team fell uncomfortable.

**Comment by joshuanapoli** [comment]
Thanks. The warning seems to be a new Actions feature, and I don't see any way to prevent it. [I mentioned the problem on github.community](https://github.community/t/unwanted-warning-for-dynamic-input-properties-to-actions/116454?u=joshuanapoli); hopefully GitHub will come up with a solution.

**Comment by joshuanapoli** [comment]
No solution is available right now. Note that https://github.com/octokit/request-action/issues/26 has the same problem.

**Comment by joshuanapoli** [comment]
The warning is new in the latest version of GitHub hosted runner, where the underlying issue is tracked: https://github.com/actions/runner/issues/514

**Comment by missedone** [comment]
thanks for the update, will watch the upstream ticket.

**Comment by metaskills** [comment]
This could be worked around by changing the interface. There could be a `keys` input which could be a hash of key/path values. The outputs could do the same.

**Comment by joshuanapoli** [comment]
> There could be a keys input which could be a hash of key/path values. The outputs could do the same.

I think that action input parameters have to be strings; a hash is not allowed.
